/* SOL FRAME — GDD Turkish (TR) translations. Loaded before the localization engine. */
window.SOL_TR = {
    "SOL FRAME": "SOL FRAME",
    "English": "İngilizce",
    "GAME DESIGN DOC": "OYUN TASARIM BELGESİ",
    "1 · Executive Summary": "1 · Yönetici Özeti",
    "2 · Vision & Pillars": "2 · Vizyon ve İlkeler",
    "3 · Story & Setting": "3 · Hikâye ve Evren",
    "4 · Audience": "4 · Hedef Kitle",
    "5 · Core Loop": "5 · Temel Döngü",
    "6 · Controls": "6 · Kontroller",
    "7 · Campaign": "7 · Kampanya",
    "8 · Wave Design": "8 · Dalga Tasarımı",
    "9 · Enemies": "9 · Düşmanlar",
    "10 · Player Systems": "10 · Oyuncu Sistemleri",
    "11 · Progression": "11 · İlerleme",
    "12 · Multiplayer": "12 · Çok Oyunculu",
    "13 · Audio": "13 · Ses",
    "14 · UI / UX": "14 · Arayüz / UX",
    "15 · Art Direction": "15 · Sanat Yönetimi",
    "16 · Technical Design": "16 · Teknik Tasarım",
    "17 · Content Inventory": "17 · İçerik Envanteri",
    "18 · Save Data": "18 · Kayıt Verisi",
    "19 · Roadmap": "19 · Yol Haritası",
    "20 · Appendix": "20 · Ek",
    "21 · Localization": "21 · Yerelleştirme",
    "GAME DESIGN DOCUMENT · v1.0": "OYUN TASARIM BELGESİ · v1.0",
    "SOL FRAMESOL DEFENSE PROTOCOL": "SOL FRAME<small>SOL SAVUNMA PROTOKOLÜ</small>",
    "16 SECTORS 6 WEAPONS 1–2 PLAYERS 3 LANGUAGES": "<span class=\"badge\">16 SEKTÖR</span><span class=\"badge\">6 SİLAH</span><span class=\"badge\">1–2 OYUNCU</span><span class=\"badge red\">3 DİL</span>",
    "Sectors": "Sektörler",
    "Score": "Puan",
    "Waves": "Dalgılar",
    "Bosses": "Patronlar",
    "Weapons": "Silahlar",
    "Difficulties": "Zorluklar",
    "Languages": "Diller",
    "Title": "Başlık",
    "Genre": "Tür",
    "Top-down vertical arcade space shooter · wave shooter · co-op": "Yukarıdan aşağı dikey arcade uzay nişancısı · dalga nişancısı · ortak oyun",
    "Modes": "Modlar",
    "Single-player · Local 2P co-op · Online co-op (PeerJS)": "Tek oyunculu · Yerel 2 kişilik ortak oyun · Çevrimiçi ortak oyun (PeerJS)",
    "Platforms": "Platformlar",
    "Windows (Electron) · Web (HTML5) · Android APK · iOS web / future IPA": "Windows (Electron) · Web (HTML5) · Android APK · iOS web / gelecekte IPA",
    "English · العربية (RTL) · 日本語": "İngilizce · Arapça (RTL) · Japonca",
    "Players": "Oyuncular",
    "Session": "Oturum",
    "3–8 min per sector · 60–90 min full campaign": "Sektör başına 3–8 dk · tam kampanya 60–90 dk",
    "View": "Görünüm",
    "2D vertical, fixed camera, top-down": "2D dikey, sabit kamera, yukarıdan aşağı",
    "Engine": "Motor",
    "Custom HTML5 Canvas + vanilla JavaScript · Web Audio · WebRTC": "Özel HTML5 Canvas + saf JavaScript · Web Audio · WebRTC",
    "Status": "Durum",
    "Ship-ready build — “SOL Defense Protocol”": "Yayına hazır derleme — “SOL Defense Protocol”",
    "Executive Summary": "Yönetici Özeti",
    "SOL Frame is a fast, neon arcade space shooter built around a single promise: become the weapon.": "SOL Frame, tek bir vaat üzerine kurulu hızlı, neon bir arcade uzay nişancısıdır: silahın kendisi ol.",
    "You pilot a lone “Frame” fighter against a 16-sector invasion — ten waves per sector, a unique dreadnought boss at the end, and a five-second salvage window before IRIS warps you onward. Guiding you is IRIS, the SOL Command AI who teaches every system as you first meet it, reacts to combat in real time, and speaks in three languages.": "16 sektörlük bir işgale karşı tek başına bir “Frame” avcı uçağını yönlendiriyorsun — sektör başına on dalga, sonunda benzersiz bir dreadnought patronu ve IRIS seni ileri ışınlamadan önce beş saniyelik bir toplama penceresi. Sana rehberlik eden, her sistemi ilk karşılaştığında öğreten, savaşa gerçek zamanlı tepki veren ve üç dilde konuşan SOL Komuta yapay zekâsı IRIS'tir.",
    "MASTERY": "USTALIK",
    "Instant mastery curve": "Anında ustalık eğrisi",
    "One input to steer, one to fire, one to launch missiles. Depth comes from heat management, weapon levels, and positioning — not from memorising bindings.": "Yönlendirmek için bir giriş, ateş için bir, füze için bir. Derinlik tuş ezberlemekten değil; ısı yönetimi, silah seviyeleri ve konumlanmadan gelir.",
    "ESCALATION": "TIRMANMA",
    "Escalation you can see": "Gözle görülür tırmanma",
    "Every sector repaints the entire battlefield — sky, nebula, planet, enemy armour and effects — so progress feels like travelling somewhere new.": "Her sektör tüm savaş alanını yeniden boyar — gökyüzü, nebula, gezegen, düşman zırhı ve efektler — böylece ilerleme yeni bir yere yolculuk gibi hissettirir.",
    "COMPANION": "YOLDAŞ",
    "A companion, not a menu": "Bir menü değil, bir yoldaş",
    "IRIS replaces tutorial text with voice and dialogue, turning onboarding into a mission briefing and combat into a conversation.": "IRIS eğitim metninin yerini ses ve diyalogla alır; başlangıcı görev brifingine, savaşı bir sohbete dönüştürür.",
    "ECONOMY": "EKONOMİ",
    "Replay-loop economy": "Tekrar oynanış döngüsü ekonomisi",
    "Food → missiles, credits → upgrades, score → extra lives, weapon crates → in-run power. Every kill can feed the engine.": "Yiyecek → füzeler, kredi → yükseltmeler, puan → ekstra canlar, silah sandıkları → koşu içi güç. Her öldürme motoru besleyebilir.",
    "Vision & Design Pillars": "Vizyon ve Tasarım İlkeleri",
    "Clarity over chaos": "Kaostan önce netlik",
    "Even at peak density the player must read threats, the HUD, and their own power state at a glance. Neon-on-black contrast, crisp hitboxes, and a heat bar that screams before it fails.": "En yoğun anda bile oyuncu tehditleri, HUD'u ve kendi güç durumunu bir bakışta okumalıdır. Siyah üzerine neon kontrast, net vuruş kutuları ve bozulmadan önce bağıran bir ısı çubuğu.",
    "Every sector is a place": "Her sektör bir yerdir",
    "The 16 sectors are not palette swaps; each owns its sky, nebula, planet, asteroid density, enemy mix, drift and boss. Warping should feel like a journey.": "16 sektör palet değişimi değildir; her birinin kendi gökyüzü, nebulası, gezegeni, asteroid yoğunluğu, düşman karışımı, sürüklenmesi ve patronu vardır. Işınlanma bir yolculuk gibi hissettirmelidir.",
    "A companion AI that earns its voice": "Sesini hak eden bir yoldaş yapay zekâ",
    "IRIS is the emotional through-line — she briefs, teaches, warns and celebrates, in the player’s own language.": "IRIS duygusal ana hattır — oyuncunun kendi dilinde brifing verir, öğretir, uyarır ve kutlar.",
    "Play anywhere, together": "Her yerde, birlikte oyna",
    "The same campaign runs on PC, browser and phone, with local and online two-player. No platform is second-class.": "Aynı kampanya PC, tarayıcı ve telefonda çalışır; yerel ve çevrimiçi iki oyunculu destekle. Hiçbir platform ikinci sınıf değildir.",
    "Respect time & device": "Zamana ve cihaza saygı",
    "Save/continue at any pause, four difficulties, particle-density scaling, three languages, mobile auto-fire.": "Her duraklatmada kaydet/devam et, dört zorluk, parçacık yoğunluğu ölçekleme, üç dil, mobil otomatik ateş.",
    "Story & Setting": "Hikâye ve Evren",
    "Humanity’s expansion into deep space — driven by the instinct to explore and to find resources — discovered worlds already inhabited by peoples strikingly like us, set apart by strange biologies and ancient augmentations. Alliances became a single union spanning many worlds.": "İnsanlığın derin uzaya yayılması — keşfetme ve kaynak bulma içgüdüsüyle — bize şaşırtıcı derecede benzeyen, ama tuhaf biyolojiler ve kadim yükseltmelerle ayrılan halkların yaşadığı dünyalar keşfetti. İttifaklar, birçok dünyayı kapsayan tek bir birliğe dönüştü.",
    "Then the union’s own connective tissue became the vector. As travel between worlds intensified, a mysterious virus spread through the population. It inflames the brain, seeding paranoid delusions that everyone nearby intends them harm. The infected become violently convinced — attacking and destroying everything they encounter, permanent dangers to all others.": "Sonra birliğin kendi bağ dokusu taşıyıcı oldu. Dünyalar arası seyahat yoğunlaşırken, nüfus arasında gizemli bir virüs yayıldı. Beyni iltihaplandırır ve yakındaki herkesin kendisine zarar vermeyi amaçladığına dair paranoyak sanrılar eker. Enfekte olanlar şiddetle inanır — karşılaştıkları her şeye saldırıp yok ederler; diğer herkes için kalıcı birer tehlikedirler.",
    "Out of the collapse, an organised invasion formed: a coordinated hostile grid of 16 sectors, each blockaded by a dreadnought. SOL Command has one answer left. You.": "Çöküşten örgütlü bir işgal doğdu: her biri bir dreadnought tarafından abluka altına alınmış, eşgüdümlü düşman bir 16 sektörlük ağ. SOL Komuta'nın tek bir cevabı kaldı. Sen.",
    "Your assignment. You are a Frame pilot — a single-seat fighter dispatched by SOL Command. Break the invasion sector by sector. Ten waves stand between you and each dreadnought. Destroy it, salvage what you can in five seconds, and IRIS warps you onward. Clear all 16 sectors and the invasion is broken.": "Görevin. Sen bir Frame pilotusun — SOL Komuta tarafından gönderilen tek kişilik bir avcı uçağı. İşgali sektör sektör kır. Her dreadnought ile aranda on dalga var. Onu yok et, beş saniyede toplayabildiğini topla ve IRIS seni ileri ışınlar. 16 sektörün tamamını temizle, işgal kırılır.",
    "IRIS — SOL Command": "IRIS — SOL Komuta",
    "IRIS is the player’s artificial-intelligence handler and only ally in a hostile grid. She appears as a masked, gem-crowned figure linked by cabling to the SOL network.": "IRIS, oyuncunun yapay zekâ irtibat subayı ve düşman bir ağdaki tek müttefikidir. SOL ağına kablolarla bağlı, maskeli ve mücevher taçlı bir figür olarak görünür.",
    "Delivers the opening tutorial in context as the player first performs each action.": "Oyuncu her eylemi ilk kez yaptığında açılış eğitimini bağlam içinde verir.",
    "Warns about overheat, hazards, boss arrival and low supply.": "Aşırı ısınma, tehlikeler, patronun gelişi ve düşük ikmal konusunda uyarır.",
    "Congratulates on weapon pickups, satellite recovery and extra lives.": "Silah toplama, uydu kurtarma ve ekstra canlar için tebrik eder.",
    "Speaks English, Arabic and Japanese with dedicated voice clips.": "İngilizce, Arapça ve Japonca konuşur; her biri için özel ses klipleri vardır.",
    "Can be muted as a voice, or silenced entirely via IRIS Transmissions.": "Sesi kısılabilir veya IRIS Yayınları ile tamamen susturulabilir.",
    "IRIS is the warm counterpoint to the cold, geometric enemy fleet — and the narrative voice of the opening.": "IRIS, soğuk ve geometrik düşman filosuna sıcak bir karşı nokta — ve açılışın anlatıcı sesidir.",
    "IRIS · SOL Command": "IRIS · SOL Komuta",
    "Bosses as antagonists": "Antagonist olarak patronlar",
    "Each dreadnought is introduced by a COMMS INCOMING transmission and taunts the player in a single, memorable line that reflects its nature.": "Her dreadnought bir “COMMS INCOMING” yayınıyla tanıtılır ve doğasını yansıtan tek, akılda kalıcı bir cümleyle oyuncuya meydan okur.",
    "Sector": "Sektör",
    "Dreadnought": "Dreadnought",
    "Taunt": "Meydan okuma",
    "Iron Veil": "Iron Veil",
    "VEIL WARDEN": "VEIL WARDEN",
    "“Iron holds this gate. You will scratch the paint, then fall.”": "“Bu kapıyı demir tutar. Boyayı çizecek, sonra düşeceksin.”",
    "Ash Orbit": "Ash Orbit",
    "CINDER HOST": "CINDER HOST",
    "“Ash in your lungs. Fire in your wake.”": "“Ciğerlerinde kül. Ardında ateş.”",
    "Rift Gate": "Rift Gate",
    "RIFT STALKER": "RIFT STALKER",
    "“The gate is a mouth. I am the teeth.”": "“Kapı bir ağızdır. Ben dişlerim.”",
    "Crimson Belt": "Crimson Belt",
    "BLOOD CROWN": "BLOOD CROWN",
    "“The belt is red for a reason. Add yours.”": "“Kemerin kırmızı olması boşuna değil. Kendininkini de ekle.”",
    "Null Cluster": "Null Cluster",
    "THE ABSENCE": "THE ABSENCE",
    "“Nothing lives here. You are the exception I will correct.”": "“Burada hiçbir şey yaşamaz. Sen düzelteceğim istisnasın.”",
    "Dread Reach": "Dread Reach",
    "DREAD NAIL": "DREAD NAIL",
    "“Reach for me. I will pin you to the dark.”": "“Bana uzan. Seni karanlığa çivileyeceğim.”",
    "Spine Corridor": "Spine Corridor",
    "SPINE TYRANT": "SPINE TYRANT",
    "“The corridor is narrow. So is your future.”": "“Koridor dar. Geleceğin de öyle.”",
    "Ember Rim": "Ember Rim",
    "CINDER QUEEN": "CINDER QUEEN",
    "“Embers first. Then the burn.”": "“Önce korlar. Sonra yanık.”",
    "Void Horizon": "Void Horizon",
    "HORIZON EYE": "HORIZON EYE",
    "“I see every vector. You have none left.”": "“Her vektörü görürüm. Sende kalmadı.”",
    "Blacksun Gate": "Blacksun Gate",
    "BLACKSUN": "BLACKSUN",
    "“Light dies at this gate. You are next.”": "“Bu kapıda ışık ölür. Sıradaki sensin.”",
    "Core Anvil": "Core Anvil",
    "ANVIL KING": "ANVIL KING",
    "“Hammer. Anvil. You are the work.”": "“Çekiç. Örs. İş parçası sensin.”",
    "Last Bastion": "Last Bastion",
    "BASTION LORD": "BASTION LORD",
    "“The last wall still stands. You will not.”": "“Son duvar hâlâ ayakta. Sen kalmayacaksın.”",
    "Wraith Edge": "Wraith Edge",
    "WRAITH": "WRAITH",
    "“Catch a ghost. Miss. Bleed.”": "“Bir hayaleti yakala. Iskala. Kan kaybet.”",
    "Storm Drift": "Storm Drift",
    "STORM REAVER": "STORM REAVER",
    "“The drift is a blade. I swing it.”": "“Sürüklenme bir bıçaktır. Onu savururum.”",
    "Scar Expanse": "Scar Expanse",
    "SCAR TITAN": "SCAR TITAN",
    "“Every scar here is a warning. Read it.”": "“Buradaki her iz bir uyarıdır. Oku onu.”",
    "Final Siege": "Final Siege",
    "LAST SIEGE": "LAST SIEGE",
    "“This is the end of the map. Make it loud.”": "“Bu haritanın sonu. Gürültülü yap.”",
    "Target Audience & Positioning": "Hedef Kitle ve Konumlandırma",
    "PRIMARY": "BİRİNCİL",
    "Ages 16–35": "16–35 yaş",
    "Arcade shooter, bullet-hell and co-op fans who love classic vertical shooters with modern polish.": "Klasik dikey nişancıları modern bir cila ile seven arcade shooter, bullet-hell ve ortak oyun hayranları.",
    "SECONDARY": "İKİNCİL",
    "Mobile players": "Mobil oyuncular",
    "Casual players who want a deep game in short, satisfying sessions.": "Kısa ve tatmin edici oturumlarda derin bir oyun isteyen gündelik oyuncular.",
    "TERTIARY": "ÜÇÜNCÜL",
    "Arabic & Japanese players": "Arapça ve Japonca oyuncular",
    "A genuine differentiator: a shooter that fully speaks their language, with RTL Arabic layout.": "Gerçek bir fark: onların dilini tam anlamıyla konuşan, RTL Arapça düzeni olan bir nişancı.",
    "Difficulty philosophy: an accessible floor with a high skill ceiling. Easy is genuinely forgiving; Extreme is a survival gauntlet that pays a 2.5× score multiplier.": "Zorluk felsefesi: erişilebilir bir taban, yüksek bir beceri tavanı. Kolay gerçekten affedicidir; Ekstrem, 2,5× puan çarpanı ödeyen bir hayatta kalma sınavıdır.",
    "Core Gameplay Loop": "Temel Oynanış Döngüsü",
    "BRIDGE — select sector, visit the Armory, adjust settings.": "KÖPRÜ — sektör seç, Cephaneliği ziyaret et, ayarları düzenle.",
    "DEPLOY — warp animation and sector briefing.": "KONUŞLANDIR — ışınlanma animasyonu ve sektör brifingi.",
    "WAVES 1–9 — survive formations, kill, collect. Steer · fire · manage heat · grab food and credits · grow weapon level · recruit satellites.": "DALGALAR 1–9 — formasyonlarda hayatta kal, öldür, topla. Yönlendir · ateş et · ısıyı yönet · yiyecek ve kredi topla · silah seviyesini büyüt · uydular topla.",
    "WAVE 10 — BOSS — COMMS INCOMING dialogue, then the dreadnought fight.": "DALGA 10 — PATRON — COMMS INCOMING diyaloğu, ardından dreadnought dövüşü.",
    "RECOVERY WINDOW (5 s) — grab every drop before warp.": "TOPLAMA PENCERESİ (5 sn) — ışınlanmadan önce her düşeni topla.",
    "WARP to the next sector · progress saved · sector unlocked · banks carried over. Repeat ×16.": "Sonraki sektöre IŞINLAN · ilerleme kaydedildi · sektör açıldı · birikimler taşındı. ×16 tekrarla.",
    "SECTOR 16 CLEARED → “INVASION BROKEN” — score, high score, new-record flourish, return to Bridge.": "SEKTÖR 16 TEMİZLENDİ → “İŞGAL KIRILDI” — puan, yüksek puan, yeni rekor süsü, Köprü'ye dönüş.",
    "Minute-to-minute loop": "Dakika dakika döngü",
    "1 · Read": "1 · Oku",
    "Identify the incoming formation and the boss telegraph.": "Gelen formasyonu ve patronun ön belirtisini tanımla.",
    "2 · Position": "2 · Konumlan",
    "Dodge lanes; keep distance from kamikaze and armoured enemies.": "Şeritlerden kaç; kamikaze ve zırhlı düşmanlardan uzak dur.",
    "3 · Fire": "3 · Ateş et",
    "Hold to shoot; watch the heat rail; release before overheat.": "Ateş için basılı tut; ısı çubuğunu izle; aşırı ısınmadan bırak.",
    "4 · Spend": "4 · Harca",
    "Missile when surrounded; satellites as a force multiplier.": "Kuşatıldığında füze; uyduları güç çarpanı olarak kullan.",
    "5 · Collect": "5 · Topla",
    "Fly over drops — every pickup is score, supply or power.": "Düşenlerin üzerinden uç — her toplama puan, ikmal veya güçtür.",
    "6 · Escalate": "6 · Tırmandır",
    "Same weapon colour raises its level; a new colour swaps the weapon but keeps the level.": "Aynı silah rengi seviyesini yükseltir; yeni bir renk silahı değiştirir ama seviyeyi korur.",
    "Controls": "Kontroller",
    "Action": "Eylem",
    "Player 1": "Oyuncu 1",
    "Player 2 (same device)": "Oyuncu 2 (aynı cihaz)",
    "Steer": "Yönlendir",
    "Mouse": "Fare",
    "Arrow keys": "Yön tuşları",
    "Fire": "Ateş",
    "Hold Left Mouse": "Sol fareyi basılı tut",
    "Hold Z": "Z'yi basılı tut",
    "Missile": "Füze",
    "Right Mouse": "Sağ fare",
    "Pause": "Duraklat",
    "Dialogue": "Diyalog",
    "Space or click": "Boşluk veya tıkla",
    "Mobile": "Mobil",
    "Touch and drag (analog)": "Dokun ve sürükle (analog)",
    "Automatic while in mission": "Görev sırasında otomatik",
    "Tap MISSILE": "FÜZE'ye dokun",
    "HUD button": "HUD düğmesi",
    "Orientation": "Ekran yönü",
    "Landscape recommended": "Yatay önerilir",
    "Design intent. On desktop the mouse is both aim and position — the single decision that makes the game instantly playable. On mobile, firing is removed as a choice so touch stays two-input and readable. Same-device 2P is disabled on mobile; cross-device co-op is fully supported.": "Tasarım amacı. Masaüstünde fare hem nişan hem konumdur — oyunu anında oynanabilir kılan tek karar. Mobilde ateş bir seçim olmaktan çıkarılır, böylece dokunmatik iki girişli ve okunaklı kalır. Aynı cihazda 2 oyuncu mobilde devre dışıdır; cihazlar arası ortak oyun tam desteklidir.",
    "Campaign Structure": "Kampanya Yapısı",
    "Sectors (chapters)": "Sektörler (bölümler)",
    "Waves per sector": "Sektör başına dalga",
    "10 — wave 10 is the boss": "10 — 10. dalga patrondur",
    "Total waves": "Toplam dalga",
    "Recovery window after boss": "Patrondan sonra toplama penceresi",
    "5 seconds": "5 saniye",
    "Unlock rule": "Kilit açma kuralı",
    "Beat sector n → unlock n+1": "Sektör n'i yen → n+1'i aç",
    "Difficulty levels": "Zorluk seviyeleri",
    "Easy · Normal · Hard · Extreme": "Kolay · Normal · Zor · Ekstrem",
    "Each sector is procedurally assembled from a hand-authored identity — sky, nebula, planet, asteroid density, enemy mix, drift and wave script — plus deterministic per-sector wave selection. Sectors are recognisable and learnable, yet varied between runs.": "Her sektör, el ile yazılmış bir kimlikten — gökyüzü, nebula, gezegen, asteroid yoğunluğu, düşman karışımı, sürüklenme ve dalga betiği — artı sektöre özgü deterministik dalga seçiminden yordamsal olarak birleştirilir. Sektörler tanınabilir ve öğrenilebilir, yine de her koşuda değişir.",
    "Sector roster — a journey across the grid": "Sektör listesi — ağ boyunca bir yolculuk",
    "SECTOR 01": "SEKTÖR 01",
    "Deep blue steel · balanced · armoured lines": "Koyu mavi çelik · dengeli · zırhlı hatlar",
    "SECTOR 02": "SEKTÖR 02",
    "Violet ash · swarm mix · falling rain": "Menekşe külü · sürü karışımı · düşen yağmur",
    "SECTOR 03": "SEKTÖR 03",
    "Crimson hot · fast · pincer & kamikaze": "Kızıl sıcak · hızlı · kıskaç ve kamikaze",
    "SECTOR 04": "SEKTÖR 04",
    "Blood red · dense packs · wedge & wall": "Kan kırmızısı · yoğun gruplar · kama ve duvar",
    "SECTOR 05": "SEKTÖR 05",
    "Grey void · thin & slow · sniper pressure": "Gri boşluk · seyrek ve yavaş · keskin nişancı baskısı",
    "SECTOR 06": "SEKTÖR 06",
    "Indigo dread · UFO-heavy · orbital rings": "Çivit korku · yoğun UFO · yörünge halkaları",
    "SECTOR 07": "SEKTÖR 07",
    "Teal corridor · narrow lanes · armoured walls": "Deniz mavisi koridor · dar şeritler · zırhlı duvarlar",
    "SECTOR 08": "SEKTÖR 08",
    "Orange ember · fast scouts · dive attacks": "Turuncu kor · hızlı keşifçiler · dalış saldırıları",
    "SECTOR 09": "SEKTÖR 09",
    "Blue horizon · UFO rings · hover pressure": "Mavi ufuk · UFO halkaları · havada asılı baskı",
    "SECTOR 10": "SEKTÖR 10",
    "Magenta eclipse · metal + UFO · lurkers": "Magenta tutulma · metal + UFO · pusuya yatanlar",
    "SECTOR 11": "SEKTÖR 11",
    "Gold forge · dense heavy armour · walls": "Altın dövme · yoğun ağır zırh · duvarlar",
    "SECTOR 12": "SEKTÖR 12",
    "Green keep · bastion formations · pincer": "Yeşil kale · tabya formasyonları · kıskaç",
    "SECTOR 13": "SEKTÖR 13",
    "Pale wraith · fast & blinking · kamikaze": "Solgun hayalet · hızlı ve göz kırpan · kamikaze",
    "SECTOR 14": "SEKTÖR 14",
    "Amber storm · dense rain · fast drift": "Kehribar fırtına · yoğun yağmur · hızlı sürüklenme",
    "SECTOR 15": "SEKTÖR 15",
    "Rose scar · metal/UFO · lurching pressure": "Gül izi · metal/UFO · sarsıntılı baskı",
    "SECTOR 16": "SEKTÖR 16",
    "Red siege · dense & fast · everything at once": "Kırmızı kuşatma · yoğun ve hızlı · her şey bir anda",
    "Wave Design": "Dalga Tasarımı",
    "Every non-boss wave is a named formation shown in the HUD. Wave size, enemy HP, spawn counts and asteroid count scale with sector and difficulty; thin/dense sector packs adjust column counts.": "Patron olmayan her dalga, HUD'da gösterilen adlandırılmış bir formasyondur. Dalga boyutu, düşman HP'si, doğma sayıları ve asteroid sayısı sektör ve zorlukla ölçeklenir; seyrek/yoğun sektör paketleri sütun sayılarını ayarlar.",
    "HUD name": "HUD adı",
    "Formation": "Formasyon",
    "Design notes": "Tasarım notları",
    "PATROL LINE": "DEVRİYE HATTI",
    "Grid, 2 rows, early spawn": "Izgara, 2 sıra, erken doğma",
    "Tutorial-friendly opening wave": "Eğitime uygun açılış dalgası",
    "SWEEP": "SÜPÜRME",
    "Staggered double line": "Kademeli çift hat",
    "Horizontal sweeps": "Yatay süpürmeler",
    "ORBIT RING": "YÖRÜNGE HALKASI",
    "Orbiting ring": "Yörüngede dönen halka",
    "UFOs from sector 5 onward": "5. sektörden itibaren UFO'lar",
    "STRAFE RUN": "YANDAN GEÇİŞ",
    "Swooping rows": "Dalan sıralar",
    "Alternating direction": "Değişen yön",
    "SCOUT SWARM": "KEŞİFÇİ SÜRÜSÜ",
    "Wide chick grid": "Geniş civciv ızgarası",
    "Fragile, numerous": "Kırılgan, çok sayıda",
    "SAUCER HUNT": "DAİRE AVI",
    "Swooping saucers": "Dalan daireler",
    "Tougher, wider hitbox": "Daha dayanıklı, daha geniş vuruş kutusu",
    "DROP PODS": "BIRAKMA KAPSÜLLERİ",
    "Parabolic drop": "Parabolik düşüş",
    "Staggered descent": "Kademeli iniş",
    "ARMORED LINE": "ZIRHLI HAT",
    "Armoured grid": "Zırhlı ızgara",
    "0.66× damage taken": "Alınan hasar 0,66×",
    "PINCER": "KIŞKAÇ",
    "Split swoop": "Bölünen dalış",
    "Kamikaze flag": "Kamikaze işareti",
    "DIVE ATTACK": "DALIŞ SALDIRISI",
    "Twin swoop": "İkiz dalış",
    "Diving enemies": "Dalan düşmanlar",
    "WEDGE": "KAMA",
    "V-formation": "V formasyonu",
    "Focused fire lane": "Odaklanmış ateş şeridi",
    "FALLING RAIN": "DÜŞEN YAĞMUR",
    "Parabolic swarm": "Parabolik sürü",
    "Continuous pressure": "Sürekli baskı",
    "WALL": "DUVAR",
    "3-row grid": "3 sıralı ızgara",
    "Metal from sector 10+": "10. sektörden itibaren metal",
    "ASTEROID FIELD": "ASTEROID ALANI",
    "Timed asteroid spawn": "Zamanlı asteroid doğması",
    "Destructible terrain": "Yok edilebilir arazi",
    "BOSS · name": "PATRON · ad",
    "Single dreadnought": "Tek dreadnought",
    "Dialogue-gated": "Diyalogla açılan",
    "Enemies": "Düşmanlar",
    "Kind": "Tür",
    "Description": "Açıklama",
    "Behaviour": "Davranış",
    "Notes": "Notlar",
    "Ordinary": "Sıradan",
    "Standard fighter": "Standart avcı",
    "Formation flight, dives, bolts": "Formasyon uçuşu, dalışlar, oklar",
    "Baseline": "Temel",
    "Chick (Scout)": "Civciv (Keşifçi)",
    "Tiny fast craft": "Küçük hızlı araç",
    "Swarms, fragile": "Sürüler, kırılgan",
    "Never drops bombs · 0.58× size · 42% food": "Asla bomba bırakmaz · 0,58× boyut · %42 yiyecek",
    "Saucer": "Daire",
    "Swoops, strafes": "Dalış yapar, yandan geçer",
    "1.2× HP · wide hitbox · bomb-capable": "1,2× HP · geniş vuruş kutusu · bomba atabilir",
    "Metal": "Metal",
    "Armoured craft": "Zırhlı araç",
    "Heavy formed lines": "Ağır düzenli hatlar",
    "0.66× damage taken · bomb-capable": "Alınan hasar 0,66× · bomba atabilir",
    "Rock": "Kaya",
    "Asteroid": "Asteroid",
    "Falls, drifts, collides": "Düşer, sürüklenir, çarpışır",
    "Destructible · 22% food · collision costs a life": "Yok edilebilir · %22 yiyecek · çarpışma bir cana mal olur",
    "Egg / Bomb": "Yumurta / Bomba",
    "Dropped explosive": "Bırakılan patlayıcı",
    "Falls, splats on contact": "Düşer, temas halinde patlar",
    "Costs a life on contact": "Temas halinde bir cana mal olur",
    "Boss": "Patron",
    "Unique movement + fire kit": "Benzersiz hareket + ateş takımı",
    "Full-screen HP bar + dialogue": "Tam ekran HP çubuğu + diyalog",
    "Boss behaviour kits": "Patron davranış takımları",
    "Bosses are data-driven from 16 distinct combinations of movement and fire patterns.": "Patronlar, hareket ve ateş desenlerinin 16 farklı kombinasyonundan veri güdümlü olarak oluşturulur.",
    "MOVEMENT sweepfigure-8dashchasestillorbitcorridorbouncehoverlurkanvilweaveblinkzigzaglurchsiege": "<span class=\"tag\">HAREKET</span><span class=\"pill cyan\">süpürme</span><span class=\"pill cyan\">8 şekli</span><span class=\"pill cyan\">atılma</span><span class=\"pill cyan\">takip</span><span class=\"pill cyan\">durma</span><span class=\"pill cyan\">yörünge</span><span class=\"pill cyan\">koridor</span><span class=\"pill cyan\">sekme</span><span class=\"pill cyan\">asılı kalma</span><span class=\"pill cyan\">pusu</span><span class=\"pill cyan\">örs</span><span class=\"pill cyan\">örgü</span><span class=\"pill cyan\">göz kırpma</span><span class=\"pill cyan\">zikzak</span><span class=\"pill cyan\">sarsılma</span><span class=\"pill cyan\">kuşatma</span>",
    "FIRE volleybombsburstspreadsniperspiralstreamringdualstitchslamneedlerainscattersiege": "<span class=\"tag red\">ATEŞ</span><span class=\"pill red\">yaylım</span><span class=\"pill red\">bombalar</span><span class=\"pill red\">patlama</span><span class=\"pill red\">yayılma</span><span class=\"pill red\">keskin nişan</span><span class=\"pill red\">sarmal</span><span class=\"pill red\">akış</span><span class=\"pill red\">halka</span><span class=\"pill red\">ikili</span><span class=\"pill red\">dikiş</span><span class=\"pill red\">çarpma</span><span class=\"pill red\">iğne</span><span class=\"pill red\">yağmur</span><span class=\"pill red\">saçılma</span><span class=\"pill red\">kuşatma</span>",
    "Escalation: bosses scale in HP, fire rate and size. LAST SIEGE is the largest and toughest (1.35× HP, 1.22× scale); ANVIL KING is the most durable (1.28× HP).": "Tırmanma: patronlar HP, ateş hızı ve boyut olarak ölçeklenir. LAST SIEGE en büyük ve en zorludur (1,35× HP, 1,22× boyut); ANVIL KING en dayanıklıdır (1,28× HP).",
    "Player Systems": "Oyuncu Sistemleri",
    "The Frame fighter": "Frame avcı uçağı",
    "HITBOX": "VURUŞ KUTUSU",
    "Smaller than its sprite — 0.7 × 0.75 of the ship box — for fair dodging.": "Sprite'ından daha küçük — gemi kutusunun 0,7 × 0,75'i — adil kaçınma için.",
    "START": "BAŞLANGIÇ",
    "3 lives and 2 missiles.": "3 can ve 2 füze.",
    "RESPAWN": "YENİDEN DOĞMA",
    "Brief invulnerability after a hit; respawn if lives remain, otherwise SYSTEM FAILURE.": "Bir isabetten sonra kısa dokunulmazlık; can kalırsa yeniden doğ, aksi halde SİSTEM ARIZASI.",
    "MOVEMENT": "HAREKET",
    "Free two-axis steering in the bottom area of the screen.": "Ekranın alt bölgesinde serbest iki eksenli yönlendirme.",
    "Weapons — six armaments": "Silahlar — altı teçhizat",
    "All weapons share a level system (0–10, shown as 11 effective tiers) that increases outlets, bullet size and damage. Same colour = +1 level; a new colour switches weapon but keeps the level.": "Tüm silahlar, çıkış sayısını, mermi boyutunu ve hasarı artıran ortak bir seviye sistemi (0–10, 11 etkin kademe olarak gösterilir) paylaşır. Aynı renk = +1 seviye; yeni renk silahı değiştirir ama seviyeyi korur.",
    "Spread bolts": "Yayılan oklar",
    "Ion Blaster": "İyon Blaster",
    "Fan of accelerated bolts. The reliable all-rounder. Heat 6.5": "Hızlandırılmış oklardan oluşan yelpaze. Güvenilir çok yönlü silah. Isı 6,5",
    "Fast straight": "Hızlı düz",
    "Neutron Gun": "Nötron Topu",
    "Narrow, high-speed projectiles; +15% damage. Heat 4.2": "Dar, yüksek hızlı mermiler; +%15 hasar. Isı 4,2",
    "Continuous lightning": "Sürekli yıldırım",
    "Lightning Fryer": "Yıldırım Kızartıcı",
    "Locks onto the nearest enemies and chains to a second target. Beam": "En yakın düşmanlara kilitlenir ve ikinci bir hedefe zincirlenir. Işın",
    "Continuous plasma": "Sürekli plazma",
    "Plasma Rifle": "Plazma Tüfeği",
    "Lock-on beams that ramp damage while held on one target. Beam": "Tek hedefte tutuldukça hasarı artan kilitlenen ışınlar. Işın",
    "Instant piercing beams": "Anında delici ışınlar",
    "Laser Cannon": "Lazer Topu",
    "Vertical beams that hit the first enemy in each lane. Heat 10": "Her şeritteki ilk düşmanı vuran dikey ışınlar. Isı 10",
    "Homing bolts": "Güdümlü oklar",
    "Photon Swarm": "Foton Sürüsü",
    "Homing bolts; at level 6+ can supercharge (red, +25% dmg). Heat 4.8": "Güdümlü oklar; 6. seviyeden itibaren aşırı güçlenebilir (kırmızı, +%25 hasar). Isı 4,8",
    "Timing + coordination: At level 10 a shot deals the full 1.08× enemy base HP. The fire interval differs per weapon (Green 7, Photon 9, Orange 10, others 8 frames), giving each a distinct rhythm.": "Zamanlama + eşgüdüm: 10. seviyede bir atış düşmanın tam 1,08× temel HP'sine denk gelir. Ateş aralığı silaha göre değişir (Yeşil 7, Foton 9, Turuncu 10, diğerleri 8 kare); bu da her birine farklı bir ritim verir.",
    "Heat & overheat": "Isı ve aşırı ısınma",
    "Heat builds with every shot or beam tick and decays when not firing. At 100% the weapon overheats and vents over ~3 seconds. Lightning and Plasma build heat fastest — sustained beams demand disciplined trigger control.": "Isı her atışta veya ışın tıkıyla artar, ateş edilmediğinde azalır. %100'de silah aşırı ısınır ve ~3 saniyede tahliye olur. Yıldırım ve Plazma en hızlı ısınır — sürekli ışınlar disiplinli tetik kontrolü gerektirir.",
    "0%WARNOVERHEAT 100%": "<span>0%</span><span>UYARI</span><span style=\"color:#ff7aa6\">AŞIRI ISINMA 100%</span>",
    "Ordnance, satellites & economy": "Mühimmat, uydular ve ekonomi",
    "MISSILES": "FÜZELER",
    "Area damage": "Alan hasarı",
    "Free, limited-stock tactical ordnance — not cooldown-based. Start with 2. Restock in the Armory or by filling the food counter (50 food = +1). Use to clear swarms and punish bosses.": "Ücretsiz, sınırlı stoklu taktik mühimmat — bekleme süresine bağlı değil. 2 ile başla. Cephanelikte veya yiyecek sayacını doldurarak (50 yiyecek = +1) yenile. Sürüleri temizlemek ve patronları cezalandırmak için kullan.",
    "SATELLITES": "UYDULAR",
    "Orbiting gun droids": "Yörüngede dönen silahlı droidler",
    "A satellite orbits the player and fires with them, extending coverage. Maximum of 2, from rare drops and the Armory.": "Bir uydu oyuncunun etrafında döner ve onunla ateş ederek kapsamı genişletir. En fazla 2; nadir düşenlerden ve Cephanelikten.",
    "Resource": "Kaynak",
    "Source": "Nereden",
    "Use": "Kullanım",
    "Food": "Yiyecek",
    "Drops — drum 1, burger 3, roast 10 units": "Düşenler — but 1, hamburger 3, rost 10 birim",
    "50 units → +1 missile; also awards score": "50 birim → +1 füze; ayrıca puan verir",
    "Credits": "Krediler",
    "Coin drops (1 or 5)": "Para düşenleri (1 veya 5)",
    "Armory — lives, missiles, satellites": "Cephanelik — canlar, füzeler, uydular",
    "Kills, pickups, bonuses": "Öldürmeler, toplamalar, bonuslar",
    "Every 100,000 → +1 life (repeatable); high score": "Her 100.000 → +1 can (tekrarlanabilir); yüksek puan",
    "Atomic / upgrade": "Atomik / yükseltme",
    "Very rare drop": "Çok nadir düşen",
    "+1 weapon level": "+1 silah seviyesi",
    "Weapon crate": "Silah sandığı",
    "Uncommon drop": "Nadir olmayan düşen",
    "Level up or switch weapon": "Seviye atla veya silah değiştir",
    "COMBO": "KOMBO",
    "Kill multiplier": "Öldürme çarpanı",
    "Consecutive kills build a combo multiplier shown in the HUD (e.g. COMBO x4), increasing score per kill and rewarding aggressive, uninterrupted play.": "Ardışık öldürmeler, HUD'da gösterilen bir kombo çarpanı oluşturur (örn. COMBO x4); öldürme başına puanı artırır ve saldırgan, kesintisiz oynanışı ödüllendirir.",
    "RECOVERY": "TOPLAMA",
    "The five-second window": "Beş saniyelik pencere",
    "When a boss dies, drops flood the screen for 5 seconds. Fly over them before IRIS warps the ship. Every boss kill becomes a short, greedy, high-adrenaline finale.": "Bir patron öldüğünde, 5 saniye boyunca ekran düşenlerle dolar. IRIS gemiyi ışınlamadan önce üzerlerinden uç. Her patron öldürme, kısa, açgözlü ve yüksek adrenalinli bir finale dönüşür.",
    "Progression & Meta": "İlerleme ve Meta",
    "IN-RUN": "KOŞU İÇİ",
    "Persistent power": "Kalıcı güç",
    "Weapon level is permanent for the run (switching colour keeps it). Satellites, missiles, lives and credits carry across sectors.": "Silah seviyesi koşu boyunca kalıcıdır (renk değiştirmek onu korur). Uydular, füzeler, canlar ve krediler sektörler arasında taşınır.",
    "SAVE": "KAYIT",
    "Continue exactly": "Tam olarak devam et",
    "Save from Pause stores sector, wave, weapon, heat, lives, missiles, satellites, score, food and P2 state. CONTINUE GAME restores it.": "Duraklat'tan kaydetmek sektör, dalga, silah, ısı, canlar, füzeler, uydular, puan, yiyecek ve 2. oyuncu durumunu saklar. OYUNA DEVAM ET bunu geri yükler.",
    "PERSIST": "KALICI",
    "Between sessions": "Oturumlar arası",
    "High score and settings persist locally. Reset Progress wipes all save data.": "Yüksek puan ve ayarlar yerel olarak kalıcıdır. İlerlemeyi Sıfırla tüm kayıt verisini siler.",
    "Armory": "Cephanelik",
    "Item": "Öğe",
    "Cost": "Maliyet",
    "Effect": "Etki",
    "LIVES": "CANLAR",
    "50 credits": "50 kredi",
    "+1 life": "+1 can",
    "75 credits": "75 kredi",
    "+5 missiles": "+5 füze",
    "SATELLITE": "UYDU",
    "150 credits": "150 kredi",
    "+1 orbiting droid (max 2)": "+1 yörünge droidi (en fazla 2)",
    "Difficulty": "Zorluk",
    "Level": "Seviye",
    "Enemy HP": "Düşman HP",
    "Enemy speed": "Düşman hızı",
    "Bomb rate": "Bomba oranı",
    "Score multiplier": "Puan çarpanı",
    "EASY": "KOLAY",
    "NORMAL": "NORMAL",
    "HARD": "ZOR",
    "EXTREME": "EKSTREM",
    "Difficulty is chosen per deployment and changes both the challenge and the reward.": "Zorluk her konuşlandırmada seçilir ve hem zorluğu hem de ödülü değiştirir.",
    "Multiplayer": "Çok Oyunculu",
    "LOCAL CO-OP": "YEREL ORTAK OYUN",
    "Same device": "Aynı cihaz",
    "Player 2 joins with Arrow keys / Z / X. Each pilot has independent lives, score, weapon, heat, food, coins and satellites. Respawn positions are offset so ships do not overlap.": "Oyuncu 2, Yön tuşları / Z / X ile katılır. Her pilotun bağımsız canları, puanı, silahı, ısısı, yiyeceği, parası ve uyduları vardır. Gemiler üst üste binmesin diye yeniden doğma konumları kaydırılır.",
    "ONLINE CO-OP": "ÇEVRİMİÇİ ORTAK OYUN",
    "Two devices": "İki cihaz",
    "Built on PeerJS peer-to-peer with six-digit room IDs. Host creates a room; guest joins with the ID; the host starts the mission. State synchronises each frame. Mobile requires two phones on the internet.": "Altı haneli oda kimlikleriyle PeerJS eşler arası üzerine kuruludur. Ev sahibi bir oda oluşturur; konuk kimlikle katılır; görevi ev sahibi başlatır. Durum her karede eşitlenir. Mobil, internete bağlı iki telefon gerektirir.",
    "Status feedback is explicit: WAITING FOR THE SECOND PLAYER… · CONNECTING… · SECOND PLAYER CONNECTED · LINK LOST.": "Durum geri bildirimi açıktır: İKİNCİ OYUNCU BEKLENİYOR… · BAĞLANIYOR… · İKİNCİ OYUNCU BAĞLANDI · BAĞLANTI KOPTU.",
    "Audio Direction": "Ses Yönetimi",
    "MUSIC": "MÜZİK",
    "Procedural engine": "Yordamsal motor",
    "Music is generated in real time via the Web Audio API: a distinct sector theme per chapter, plus a boss arrangement that switches on dreadnought arrival or dialogue. Lead, percussion and bass respond to mode with deterministic per-sector seeds.": "Müzik, Web Audio API aracılığıyla gerçek zamanlı üretilir: her bölüm için farklı bir sektör teması, ayrıca dreadnought geldiğinde veya diyalogda değişen bir patron düzenlemesi. Solo, perküsyon ve bas, sektöre özgü deterministik tohumlarla moda tepki verir.",
    "SFX": "SFX",
    "Combat texture": "Savaş dokusu",
    "Per-weapon fire, missiles, explosions, pickups, UI, splats, warps and boss impacts. SFX volume is independently adjustable.": "Silaha özgü ateş, füzeler, patlamalar, toplamalar, arayüz, sıçramalar, ışınlanmalar ve patron etkileri. SFX ses düzeyi bağımsız olarak ayarlanabilir.",
    "VOICE": "SES",
    "IRIS in 3 languages": "IRIS 3 dilde",
    "16 events × 3 languages = 48 pre-rendered clips, covering tutorial, lives, missiles, mission briefing, heat, overheat, hazards, weapon, food, coins, satellite, rocks, boss, loot, P2 and save.": "16 olay × 3 dil = 48 önceden işlenmiş klip; eğitim, canlar, füzeler, görev brifingi, ısı, aşırı ısınma, tehlikeler, silah, yiyecek, paralar, uydu, kayalar, patron, ganimet, 2. oyuncu ve kaydı kapsar.",
    "Two independent toggles: IRIS Transmissions (tips) and IRIS Voice (audio).": "İki bağımsız anahtar: IRIS Yayınları (ipuçları) ve IRIS Sesi (ses).",
    "UI / UX & HUD": "Arayüz / UX ve HUD",
    "IN-MISSION": "GÖREV İÇİ",
    "HUD": "HUD",
    "Top-left: score, hearts, credits, missiles, weapon icon + level, food (x/50), combo": "Sol üst: puan, kalpler, krediler, füzeler, silah simgesi + seviye, yiyecek (x/50), kombo",
    "Top-centre: SECTOR n · WAVE n/10": "Üst orta: SEKTÖR n · DALGA n/10",
    "Heat rail: weapon temperature with warn/overheat states": "Isı çubuğu: uyarı/aşırı ısınma durumlarıyla silah sıcaklığı",
    "Boss bar: appears only for dreadnoughts": "Patron çubuğu: yalnızca dreadnought'lar için görünür",
    "Boss dialog: “COMMS INCOMING” panel, click/space to dismiss": "Patron diyaloğu: “COMMS INCOMING” paneli, kapatmak için tıkla/boşluk",
    "P2 HUD: second set of indicators in co-op": "2. oyuncu HUD'u: ortak oyunda ikinci gösterge seti",
    "MENUS": "MENÜLER",
    "Screens": "Ekranlar",
    "Bridge: high score, Continue, Start Mission, Multiplayer, Armory, Settings, Exit": "Köprü: yüksek puan, Devam Et, Görevi Başlat, Çok Oyunculu, Cephanelik, Ayarlar, Çıkış",
    "Sector Navigation: 16-node grid, unlocked nodes interactive": "Sektör Navigasyonu: 16 düğümlü ızgara, açılan düğümler etkileşimli",
    "Armory: credits and three purchasables": "Cephanelik: krediler ve üç satın alınabilir öğe",
    "Pause: Resume, Save, Armory, Restart, Main Menu": "Duraklat: Devam, Kaydet, Cephanelik, Yeniden Başlat, Ana Menü",
    "Settings: audio, particles, language, fullscreen, IRIS toggles, reset": "Ayarlar: ses, parçacıklar, dil, tam ekran, IRIS anahtarları, sıfırlama",
    "Game Over: SYSTEM FAILURE, score, new-record flourish": "Oyun Bitti: SİSTEM ARIZASI, puan, yeni rekor süsü",
    "Multiplayer: host / join / status panels": "Çok Oyunculu: ev sahibi / katıl / durum panelleri",
    "Accessibility & inclusivity": "Erişilebilirlik ve kapsayıcılık",
    "Three full languages": "Üç tam dil",
    "Including RTL Arabic layout with mirrored typography and alignment.": "Aynalı tipografi ve hizalamayla RTL Arapça düzeni dahil.",
    "Per-language fonts": "Dile özgü yazı tipleri",
    "Rajdhani/Orbitron for Latin, Cairo for Arabic, Noto Sans JP for Japanese.": "Latin için Rajdhani/Orbitron, Arapça için Cairo, Japonca için Noto Sans JP.",
    "Performance scaling": "Performans ölçekleme",
    "Particle density setting: Low / Medium / Ultra.": "Parçacık yoğunluğu ayarı: Düşük / Orta / Ultra.",
    "Skip-friendly teaching": "Atlanabilir eğitim",
    "IRIS transmissions can be skipped; seen tips are remembered and not repeated.": "IRIS yayınları atlanabilir; görülen ipuçları hatırlanır ve tekrarlanmaz.",
    "Mobile comfort": "Mobil konfor",
    "Auto-fire while in mission; landscape guidance.": "Görev sırasında otomatik ateş; yatay yönlendirme.",
    "Reduced motion": "Azaltılmış hareket",
    "Animations and transitions disabled for users who prefer less motion.": "Daha az hareket isteyen kullanıcılar için animasyonlar ve geçişler devre dışı bırakılır.",
    "Art Direction": "Sanat Yönetimi",
    "Neon vector minimalism on deep-space black. Flat-shaded geometric craft, clean silhouettes, soft glows, starfields and parallax nebulae. Enemies are deliberately cute-menacing — smiley saucers and simple icons made sinister by scale and context. The player is a small, bright triangle of cyan/white light. Weapons are the spectacle: lightning arcs, plasma beams, piercing lasers, homing photons.": "Derin uzay siyahı üzerine neon vektör minimalizmi. Düz gölgeli geometrik araçlar, temiz siluetler, yumuşak parıltılar, yıldız alanları ve paralaks nebulalar. Düşmanlar kasıtlı olarak sevimli-tehditkârdır — gülümseyen daireler ve basit simgeler, ölçek ve bağlamla ürkütücü hale gelir. Oyuncu, camgöbeği/beyaz ışıktan küçük, parlak bir üçgendir. Silahlar gösterinin kendisidir: yıldırım yayları, plazma ışınları, delici lazerler, güdümlü fotonlar.",
    "Live gameplay — plasma beams carving a dreadnought escort screen in a red sector.": "Canlı oynanış — kırmızı bir sektörde plazma ışınları bir dreadnought eskort perdesini yarıyor.",
    "SECTOR THEMING": "SEKTÖR TEMALARI",
    "Every sector repaints the field": "Her sektör alanı yeniden boyar",
    "Sky gradient, nebula colour, planet tint, enemy vest/skin, bolt colour, aura and meteor density. Sectors 5, 10 and 13 are deliberately “dark” unlit voids — they feel wrong and hostile.": "Gökyüzü degradesi, nebula rengi, gezegen tonu, düşman yeleği/derisi, ok rengi, aura ve meteor yoğunluğu. 5, 10 ve 13. sektörler kasıtlı olarak “karanlık” ışıksız boşluklardır — yanlış ve düşmanca hissettirirler.",
    "BRAND": "MARKA",
    "Logo & key art": "Logo ve ana görsel",
    "Wordmark SOL FRAME in glowing yellow Orbitron with the subtitle SOL DEFENSE PROTOCOL. Key art shows the Frame fighter unleashing plasma against a red dreadnought and escorts. IRIS key art depicts the gem-crowned SOL Command AI.": "Parıldayan sarı Orbitron ile SOL FRAME kelime markası ve SOL DEFENSE PROTOCOL alt başlığı. Ana görsel, Frame avcı uçağının kırmızı bir dreadnought ve eskortlarına karşı plazma saldığını gösterir. IRIS ana görseli, mücevher taçlı SOL Komuta yapay zekâsını betimler.",
    "Cover composition — the neon wordmark over live combat.": "Kapak kompozisyonu — canlı savaşın üzerinde neon kelime markası.",
    "Technical Design": "Teknik Tasarım",
    "Layer": "Katman",
    "Implementation": "Uygulama",
    "Rendering": "İşleme",
    "HTML5 Canvas 2D; procedural sprites painted to offscreen canvases and cached": "HTML5 Canvas 2D; ekran dışı tuvallere çizilip önbelleğe alınan yordamsal sprite'lar",
    "Logic": "Mantık",
    "Vanilla JavaScript; objects for bullets/particles; fixed update ticks": "Saf JavaScript; mermiler/parçacıklar için nesneler; sabit güncelleme tikleri",
    "Audio": "Ses",
    "Web Audio API — procedural music + pre-rendered IRIS voice clips (MP3)": "Web Audio API — yordamsal müzik + önceden işlenmiş IRIS ses klipleri (MP3)",
    "Networking": "Ağ",
    "PeerJS (WebRTC data channels), six-digit room IDs": "PeerJS (WebRTC veri kanalları), altı haneli oda kimlikleri",
    "Persistence": "Kalıcılık",
    "localStorage — settings, high score, run save": "localStorage — ayarlar, yüksek puan, koşu kaydı",
    "Desktop build": "Masaüstü derlemesi",
    "Electron wrapper — 2-Windows/, SOL Frame.exe": "Electron sarmalayıcı — 2-Windows/, SOL Frame.exe",
    "Web build": "Web derlemesi",
    "Self-contained SOL Frame.html + peerjs.min.js + iris/": "Kendi kendine yeten SOL Frame.html + peerjs.min.js + iris/",
    "Mobile build": "Mobil derlemesi",
    "Capacitor / Android project → APK; installable web app": "Capacitor / Android projesi → APK; kurulabilir web uygulaması",
    "manifest.json — fullscreen, theme #010103": "manifest.json — tam ekran, tema #010103",
    "PLATFORM MATRIX": "PLATFORM MATRİSİ",
    "Portable .exe, no install": "Taşınabilir .exe, kurulum gerekmez",
    "Static hosting or local file": "Statik barındırma veya yerel dosya",
    "APK via Android Studio": "Android Studio ile APK",
    "Safari Home Screen, or Mac + Xcode IPA": "Safari Ana Ekranı veya Mac + Xcode IPA",
    "PERFORMANCE TARGETS": "PERFORMANS HEDEFLERİ",
    "60 FPS on mid-range laptops and modern phones at Medium particles.": "Orta seviye dizüstü ve modern telefonlarda Orta parçacıklarla 60 FPS.",
    "Particle-density setting protects frame-rate on low-end devices.": "Parçacık yoğunluğu ayarı, düşük seviye cihazlarda kare hızını korur.",
    "Sprite caching avoids per-frame vector redraws.": "Sprite önbellekleme, kare başına vektör yeniden çizimini önler.",
    "Content Inventory": "İçerik Envanteri",
    "Waves / sector": "Dalga / sektör",
    "Unique bosses": "Benzersiz patronlar",
    "Wave events": "Dalga olayları",
    "Enemy kinds": "Düşman türleri",
    "Weapon tiers": "Silah kademeleri",
    "IRIS voice events": "IRIS ses olayları",
    "Drop types": "Düşme türleri",
    "Save Data & Settings": "Kayıt Verisi ve Ayarlar",
    "Key": "Anahtar",
    "Stored": "Saklanan",
    "High score": "Yüksek puan",
    "Language": "Dil",
    "Volumes (master / SFX / music)": "Ses düzeyleri (ana / SFX / müzik)",
    "Particle density": "Parçacık yoğunluğu",
    "IRIS tips / voice toggles": "IRIS ipucu / ses anahtarları",
    "Seen tutorial tips": "Görülen eğitim ipuçları",
    "In-run save": "Koşu içi kayıt",
    "Serialised run state (sector, wave, ship stats, banks, P2)": "Serileştirilmiş koşu durumu (sektör, dalga, gemi istatistikleri, birikimler, 2. oyuncu)",
    "Future / Post-Launch Roadmap": "Gelecek / Çıkış Sonrası Yol Haritası",
    "NEAR-TERM": "YAKIN VADE",
    "More to master": "Ustalaşacak daha çok şey",
    "New sector variants & boss kits after sector 16": "16. sektörden sonra yeni sektör varyantları ve patron takımları",
    "Endless / survival mode from the existing generator": "Mevcut üreticiden sonsuz / hayatta kalma modu",
    "Online leaderboards": "Çevrimiçi liderlik tabloları",
    "Achievements & unlockable ship skins": "Başarımlar ve açılabilir gemi görünümleri",
    "MEDIUM-TERM": "ORTA VADE",
    "Wider reach": "Daha geniş erişim",
    "iOS App Store release (signed IPA)": "iOS App Store sürümü (imzalı IPA)",
    "IRIS inter-sector story transmissions": "IRIS sektörler arası hikâye yayınları",
    "Additional languages via a voice pipeline": "Ses hattı üzerinden ek diller",
    "Remappable controls & gamepad support": "Yeniden atanabilir kontroller ve gamepad desteği",
    "LONG-TERM": "UZUN VADE",
    "Ecosystem": "Ekosistem",
    "Sector / wave editor from the data-driven traits system": "Veri güdümlü özellik sisteminden sektör / dalga düzenleyicisi",
    "Competitive co-op scoring": "Rekabetçi ortak oyun puanlaması",
    "Ghost replays": "Hayalet tekrarları",
    "Appendix — Build & Play": "Ek — Derleme ve Oynanış",
    "PLAY FROM SOURCE": "KAYNAKTAN OYNA",
    "Browser: open 1-Game/SOL Frame.html": "Tarayıcı: 1-Game/SOL Frame.html dosyasını aç",
    "Windows: run 2-Windows/SOL Frame.exe": "Windows: 2-Windows/SOL Frame.exe dosyasını çalıştır",
    "Mobile: install the APK, or host 1-Game/ over HTTPS": "Mobil: APK'yı kur veya 1-Game/ klasörünü HTTPS üzerinden barındır",
    "REBUILD PROMO IMAGES": "TANITIM GÖRSELLERİNİ YENİDEN OLUŞTUR",
    "cd 6-Promo && ./build.sh": "cd 6-Promo && ./build.sh",
    "Needs Node, Python + Pillow and Microsoft Edge. The pipeline poses the real renderer and screenshots it headlessly.": "Node, Python + Pillow ve Microsoft Edge gerektirir. Hat, gerçek işleyiciyi konumlandırır ve başsız olarak ekran görüntüsü alır.",
    "REGENERATE IRIS VOICE": "IRIS SESİNİ YENİDEN ÜRET",
    "python _iris_tts.py": "python _iris_tts.py",
    "Produces the 48 MP3 clips across English, Arabic and Japanese.": "İngilizce, Arapça ve Japonca boyunca 48 MP3 klibi üretir.",
    "MOBILE BUILD": "MOBİL DERLEME",
    "cd mobilenode sync.js && npx cap sync android": "cd mobilenode sync.js && npx cap sync android",
    "Then Build > Build APK(s) in Android Studio.": "Ardından Android Studio'da Build > Build APK(s).",
    "Designed, built and voiced as a complete arcade campaign.This document describes the shipped build and is the canonical reference for future content.": "Eksiksiz bir arcade kampanyası olarak tasarlandı, inşa edildi ve seslendirildi.Bu belge, yayınlanan derlemeyi tanımlar ve gelecekteki içerik için kanonik referanstır.",
    "Localization & Language Switching": "Yerelleştirme ve Dil Değiştirme",
    "SOL Frame launches with three fully supported locales — English, العربية (Arabic, RTL) and 日本語 (Japanese). Language is a live runtime setting, not a build-time choice: the player opens Settings → 言語 / LANGUAGE, picks a locale, and every menu, HUD label, tutorial transmission and IRIS line re-renders instantly — no reload, no lost progress.": "SOL Frame üç tam destekli yerel ayarla çıkıyor — İngilizce, Arapça (RTL) ve Japonca. Dil, derleme zamanı seçimi değil, canlı bir çalışma zamanı ayarıdır: oyuncu Ayarlar → DİL / LANGUAGE menüsünü açar, bir yerel ayar seçer ve her menü, HUD etiketi, eğitim yayını ve IRIS satırı anında yeniden çizilir — yeniden yükleme yok, ilerleme kaybı yok.",
    "Design intent. One data-driven LOCALES table feeds the entire interface. A locale is data, not code — shipping a fourth language means adding one locale block, a font stack and a voice set, with no changes to game logic.": "Tasarım amacı. Tek bir veri güdümlü LOCALES tablosu tüm arayüzü besler. Bir yerel ayar kod değil veridir — dördüncü bir dil yayınlamak, oyun mantığında hiçbir değişiklik yapmadan bir yerel ayar bloğu, bir yazı tipi yığını ve bir ses seti eklemek anlamına gelir.",
    "Try it live. Use the AR / JP / KO / EN switch at the top-right of this page to translate the entire document — headings, tables, captions and this section included. The choice is remembered in your browser.": "Canlı deneyin. Bu sayfanın sağ üst köşesindeki AR / JP / KO / EN anahtarını kullanarak tüm belgeyi çevirin — başlıklar, tablolar, alt yazılar ve bu bölüm dahil. Seçim tarayıcınızda hatırlanır.",
    "Localization matrix": "Yerelleştirme matrisi",
    "Representative interface strings across all three shipped locales. The Japanese column uses natural, game-native phrasing (e.g. 兵装庫 for the Armory, システム障害 for System Failure) rather than a literal translation.": "Yayınlanan üç yerel ayar genelinde temsili arayüz metinleri. Japonca sütunu, birebir çeviri yerine doğal, oyuna özgü ifadeler kullanır (örn. Cephanelik için 兵装庫, Sistem Arızası için システム障害).",
    "Language switching — runtime flow": "Dil değiştirme — çalışma zamanı akışı",
    "Player opens 設定 / Settings and taps the 言語 / LANGUAGE selector.": "Oyuncu Ayarlar menüsünü açar ve DİL / LANGUAGE seçicisine dokunur.",
    "setLanguage(lang) is called — en, ar or jp.": "setLanguage(lang) çağrılır — en, ar veya jp.",
    "The active LOCALES block is swapped and all bound labels re-render in place.": "Etkin LOCALES bloğu değiştirilir ve bağlı tüm etiketler yerinde yeniden çizilir.",
    "<html lang> is updated; rtl is toggled for Arabic; the Japanese font stack is enabled.": "<html lang> güncellenir; Arapça için rtl açılır; Japonca yazı tipi yığını etkinleştirilir.",
    "The choice is written to localStorage and restored on the next launch.": "Seçim localStorage'a yazılır ve sonraki başlatmada geri yüklenir.",
    "Typography & layout per language": "Dile göre tipografi ve düzen",
    "LATIN": "LATİN",
    "Rajdhani for body copy and Orbitron for headings. Standard left-to-right layout with condensed, uppercase HUD labels.": "Gövde metni için Rajdhani, başlıklar için Orbitron. Sıkıştırılmış, büyük harfli HUD etiketleriyle standart soldan sağa düzen.",
    "RTL": "RTL",
    "Cairo typeface with a mirrored interface: text alignment, HUD ordering and padding flip for right-to-left reading. Punctuation and numerals follow Arabic conventions.": "Aynalı arayüzle Cairo yazı tipi: sağdan sola okuma için metin hizalaması, HUD sıralaması ve dolgu ters çevrilir. Noktalama ve rakamlar Arapça geleneklerini izler.",
    "CJK": "CJK",
    "Noto Sans JP with relaxed letter-spacing and non-uppercase labels, since full-width characters do not need tracking. Japanese line-breaking avoids orphaning short particles.": "Tam genişlikteki karakterler izleme gerektirmediğinden, gevşek harf aralığı ve büyük harf olmayan etiketlerle Noto Sans JP. Japonca satır sonlama, kısa parçacıkların yalnız kalmasını önler.",
    "Voice & audio per language": "Dile göre ses ve seslendirme",
    "Every IRIS tutorial and reaction line exists as a pre-rendered clip in all three languages — 16 events × 3 languages = 48 MP3 files under iris/ (for example ja-heat.mp3 and ar-heat.mp3). If a clip is missing, the game falls back to the browser's Speech Synthesis API using the locale's BCP-47 tag (ja-JP, ar-SA, en-US) before finally falling back to English text.": "Her IRIS eğitim ve tepki satırı üç dilde önceden işlenmiş bir klip olarak bulunur — 16 olay × 3 dil = iris/ altında 48 MP3 dosyası (örneğin ja-heat.mp3 ve ar-heat.mp3). Bir klip eksikse, oyun yerel ayarın BCP-47 etiketini (ja-JP, ar-SA, en-US) kullanan tarayıcı Speech Synthesis API'sine, en sonunda İngilizce metne geri döner.",
    "Safe switching. Changing language mid-run never interrupts play: the active wave, weapon level, heat and banks are all language-agnostic. Only visible copy changes. Arabic also preserves the numeric HUD values untouched.": "Güvenli değiştirme. Koşu ortasında dil değiştirmek oyunu asla kesmez: etkin dalga, silah seviyesi, ısı ve birikimler dilden bağımsızdır. Yalnızca görünen metin değişir. Arapça ayrıca sayısal HUD değerlerini olduğu gibi korur.",
    "Adding a fourth language": "Dördüncü bir dil eklemek",
    "DATA": "VERİ",
    "Locale block": "Yerel ayar bloğu",
    "Add one entry to LOCALES with the same key set. Missing keys automatically fall back to en, so a partial locale is safe to ship and refine.": "LOCALES'e aynı anahtar setiyle bir girdi ekle. Eksik anahtarlar otomatik olarak en'e geri döner, böylece kısmi bir yerel ayar güvenle yayınlanıp iyileştirilebilir.",
    "ASSETS": "VARLIKLAR",
    "Fonts & voice": "Yazı tipleri ve ses",
    "Register a font stack for the script and generate the 16 IRIS clips via python _iris_tts.py. No gameplay code changes are required.": "Betik için bir yazı tipi yığını kaydet ve python _iris_tts.py ile 16 IRIS klibini üret. Oynanış kodunda değişiklik gerekmez.",
    "SOL Frame": "SOL Frame",
    "SOL DEFENSE PROTOCOL v1.0": "SOL DEFENSE PROTOCOL v1.0",
    "Windows": "Windows",
    "Web": "Web",
    "Android": "Android"
};
